# ********************************************************************************
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made
# available under the terms of the Apache Software License 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: Apache-2.0
# ********************************************************************************

---
name: Code Freeze New freeze Bot

# Controls when the workflow will run
on:
  pull_request_target:
    branches:
      - '*'
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  codefreeze_branch_check:
    uses: andrew-m-leonard/openjdk-build/.github/workflows/code-freeze-regex-branch.yml@master
    with:
      branch-regex: "^ma.*er$"

  codefreeze_if_branch_match:
    needs: codefreeze_branch_check
    uses: andrew-m-leonard/openjdk-build/.github/workflows/code-freeze-master.yml@master
    if: (github.event_name == 'pull_request_target' || (github.event_name == 'issue_comment' && github.event.issue.pull_request)) && needs.codefreeze_branch_check.outputs.regex-matches == 'true'
    secrets: inherit

